# MySQL configuration.
datebase:
  hostname: 'localhost'
  port: 3306
  username: 'root'
  datebase: 'discordRewards'
  password: 'password'
# Discord bot configuration.
bot:
  token: 'your_bot_token!'
  status: 'q1zZ-DiscordRewards v0.3'
# Available methods: MySQL, Flat
data:
  savetype: 'MySQL'
# Receiving reward settings.
settings:
  # Id of channel to receiving reward
  channelid: '826894120471494697'
  # blocks the possibility of receiving a reward
  # to multiple nicks from one discord account.
  # Working only for MySQL. If you want to get a similar
  # effect for a different type of save, you can use assigning a role
  doubleverification: true
# Reward settings.
reward:
  # id of discord role. Player will get this role
  # when received reward. To disable set 'disable'
  roleid: 'disable'
  # commands executed when receiving the reward
  commands:
    - give %player% diamond 1
  # broadcast will be sent when received the reward
  broadcast:
    - '&8&m--------------------------'
    - ' '
    - '&8» &fPlayer &9%player% &fclaimed the discord reward!'
    - ' '
    - '&8» &7Discord: &fhttps://discord.gg/ynqmeCKV'
    - ' '
    - '&8&m--------------------------'
messages:
  embeds:
    # User entered wrong nickname.
    wrongNickname:
      # embed title.
      title: 'ERROR!'
      # embed description. To create new line use, %newline%
      description: '%mention% > You entered the wrong nickname!'
      # in hex format.
      color: '#ff0000'
    # Player is offline.
    playerOffline:
      # embed title.
      title: 'ERROR!'
      # embed description. To create new line use, %newline%
      description: '%mention% > You must be online on the server!'
      # in hex format.
      color: '#ff0000'
    # Reward has been already received.
    alreadyReceived:
      # embed title.
      title: 'ERROR!'
      # embed description. To create new line use, %newline%
      description: '%mention% > Reward already been received!'
      # in hex format.
      color: '#ff0000'
    # Reward has been successfully received.
    successfulReceived:
      # embed title.
      title: 'SUCCES!'
      # embed description. To create new line use, %newline%
      description: '%mention% > You successfully received reward to **%nick%**!'
      # in hex format.
      color: '#00ff44'




