# EN: Database connection settings.
# PL: Konfiguracja połączenia bazy danych.
mysql:
  host: 'localhost'
  port: 3306
  database: 'db_name'
  username: 'root'
  password: 'password123%$@'
# EN: Discord bot configuration.
# PL: Konfiguracja bota discord.
bot:
  # EN: Bot token from https://discord.com/developers/applications
  # PL: Token bota z strony https://discord.com/developers/applications
  token: 'your_bot_token!'
  # EN: Bot status
  # PL: Status bota
  status: 'q1zZ-DiscordRewards v0.4'
# EN: Settings
# PL: Ustawienia
settings:
  # EN: Minecraft nickname regex for checking if nickname is valid.
  # PL: Regex dla nicków minecraft do sprawdzania poprawności nicku.
  nickname-regex: '[a-zA-Z0-9_]+'
  # EN: Id of discord channel for receiving rewards.
  # PL: Id kanału z discorda do odbierania nagrody.
  discordChannelID: '826444933547425882'
# EN: Rewards settings.
# PL: Ustawienia nagród.
rewards:
  # EN: This commands will be executed when player receive reward.
  # PL: Komendy zostaną wykonane po odbiorze nagrody.
  commands:
    - 'give %player% diamond 1'
  # EN: This roles will be added to user on discord when receive reward.
  # PL: Te role zostaną dodane do użytkownika na discordzie po odbiorze nagrody.
  roles:
    - '826444933547425886'
  # EN: Broadcast when player receive reward.
  # PL: Ogłoszenie gdy gracz odbierze nagrodę.
  broadcast:
    - ' '
    - '&8» &fPlayer &9%player% &freceived the discord reward!'
    - '&8» &fDiscord link: &9&nhttps://discord.com/xxxxxx'
    - ' '
# EN: Messages configuration
# PL: Konfiguracja wiadomości
messages:
  embeds:
    # User entered wrong nickname.
    wrongNickname:
      # embed title.
      title: 'ERROR!'
      # embed description. To create new line use, %newline%
      description: '%mention% > You entered the wrong nickname!'
      # in hex format.
      color: '#ff0000'
      # Embed thumbnail url.
      # Set empty ('') to disable.
      thumbnail_url: ''
    # Player is offline.
    playerOffline:
      # embed title.
      title: 'ERROR!'
      # embed description. To create new line use, %newline%
      description: '%mention% > You must be online on the server!'
      # in hex format.
      color: '#ff0000'
      # Embed thumbnail url.
      # Set empty ('') to disable.
      thumbnail_url: ''
    # Reward has been already received.
    alreadyReceived:
      # embed title.
      title: 'ERROR!'
      # embed description. To create new line use, %newline%
      description: '%mention% > Reward already been received!'
      # in hex format.
      color: '#ff0000'
      # Embed thumbnail url.
      # Set empty ('') to disable.
      thumbnail_url: ''
    # Reward has been successfully received.
    successfulReceived:
      # embed title.
      title: 'SUCCES!'
      # embed description. To create new line use, %newline%
      description: '%mention% > You successfully received reward to **%nick%**!'
      # in hex format.
      color: '#00ff44'
      # Embed thumbnail url.
      # Set empty ('') to disable.
      thumbnail_url: ''