name: q1zZ-DiscordRewards
version: 0.4
main: me.q1zz.discordrewards.DiscordReward
author: q1zZ
description: Simple plugin for receiving reward for join to discord server.
website: https://github.com/q1zZu